#!/bin/bash

echo -e "installing conky..."
sudo apt-get -qq install conky-all

echo -e "verifying ~/.fonts directory..."
mkdir -p ~/.fonts

echo -e "adding font and updating cache..."
cp poiret-one/PoiretOne-Regular.ttf /home/$USER/.fonts/
fc-cache -f

echo -e "berifying wetch path..."
repo_path="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
sed -i "s|PLACEHOLDER_WETCH_PATH|${repo_path}|g" "$repo_path"/src/*

echo -e done
